brew "openjdk"
brew "act"

cask "keepingyouawake"
cask "spotify"
cask "adobe-acrobat-reader"
cask "steam"
cask "skype"
cask "paw"
cask "dupeguru"
cask "disk-inventory-x"
cask "hey"
cask "dropbox"
cask "dotnet-sdk"
cask "domination"
cask "docker"
