tap "basecamp/tap"

brew "python"
brew "gnupg"
brew "awscli"
brew "node"
brew "vegeta"
brew "rsync"
brew "librsvg"

cask "spotify"
cask "adobe-acrobat-reader"
cask "steam"
cask "rapidapi"
cask "hey-desktop"
cask "basecamp/tap/hey"
cask "dropbox"
cask "nef10/tap/domination"
cask "docker-desktop"
cask "balenaetcher"
cask "vlc"
cask "handbrake-app"
cask "gramps"
cask "mitmproxy"
cask "discord"
cask "microsoft-auto-update"
cask "microsoft-teams"

mas "Brother iPrint&Scan", id: 1193539993
