brew "act"
brew "gnupg"
brew "mitmproxy"

cask "keepingyouawake"
cask "spotify"
cask "adobe-acrobat-reader"
cask "steam"
cask "skype"
cask "paw"
cask "dupeguru"
cask "disk-inventory-x"
cask "hey"
cask "dropbox"
cask "dotnet-sdk"
cask "domination"
cask "docker"
cask "latest"
cask "balenaetcher"
cask "temurin"
cask "alfred"
cask "vlc"

mas "Quiver", id: 866773894
