format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$dotnet\
$golang\
$helm\
$nodejs\
$java\
$kotlin\
$php\
$python\
$rlang\
$ruby\
$swift\
$terraform\
$vagrant\
$conda\
$memory_usage\
$openstack\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
${custom.architecture}\
$character"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[status]
disabled = false

[directory]
read_only = " 🔒"

[aws]
disabled = true

[git_metrics]
disabled = false

[git_status]
stashed = ""
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
ahead = "⇡${count}"
behind = "⇣${count}"

[java]
style = "52"

[nodejs]
symbol = "⬢ "

[custom.architecture]
description = "Architecture when using Rosetta 2"
when = """[ "$(sysctl -in sysctl.proc_translated)" = "1" ]"""
format = "[ Rosetta ](242)"
shell = ["bash", "--noprofile", "--norc"]
